language: csharp
mono: 5.2.0
dotnet: 3.1.0

install:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
  #- curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - dotnet restore

script:
  - dotnet build -c Debug --no-restore -v m
  #- dotnet test Jenkins.Net.Tests/Jenkins.Net.Tests.csproj -c Debug --no-build --filter Category=Unit
  - dotnet pack Dapper.Scripts/Dapper.Scripts.csproj -c Debug --no-build --no-restore -o bin

deploy:
  provider: releases
  api_key: $GITHUB_APIKEY
  file: "Dapper.Scripts/bin/Dapper.Scripts.*.nupkg"
  skip_cleanup: true
  on:
    tags: true

# deploy:
#   skip_cleanup: true
#   provider: script
#   script: dotnet nuget push Jenkins.Net/bin/jenkinsnet.*.nupkg -k $NUGET_APIKEY -s $NUGET_SOURCE
#   on:
#     branch: master