language: csharp
mono: 5.2.0
#mono: none
dotnet: 3.1

install:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
  - dotnet restore

script:
  - dotnet pack Dapper.Scripts/Dapper.Scripts.csproj -c Release --no-restore -o bin

deploy:
  provider: releases
  api_key: $GITHUB_APIKEY
  file: "Dapper.Scripts/bin/Dapper.Scripts.*.nupkg"
  skip_cleanup: true
  on:
    branch: master

deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push "Dapper.Scripts/bin/Dapper.Scripts.*.nupkg" --source "github"
  on:
    branch: master
